#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# AIX/3/check_cron - 06/14/93
#
#-----------------------------------------------------------------------------
#
if [ -f /usr/spool/cron/crontabs/$1 ]; then
  echo "YES"
else
  echo "NO"
fi
