#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# AIX/3/gen_bootparam_sets - 06/14/93
#
#-----------------------------------------------------------------------------
#

[ -r /etc/bootparams ] && {
  $SED -e 's/#.*$//' /etc/bootparams |
  $SED -e '/^[ \t]*$/d' |
  $AWK '
       BEGIN {LINE="";}
       /\\\\$/ {LINE=LINE " " substr($0, 1, length($0)-1);}
       !/\\\\$/ {print LINE $0; LINE="";}
  ' > $WORKDIR/etc_bootparams.$$
  echo "/etc/bootparams" > $WORKDIR/etc_bootparams.$$.src
  echo "$WORKDIR/etc_bootparams.$$"
}

[ -n "$YP" ] && {
  $YPCAT bootparams > $WORKDIR/nis_bootparams.$$
  echo "NIS" > $WORKDIR/nis_bootparams.$$.src
  echo "$WORKDIR/nis_bootparams.$$"
}
