#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# AIX/3/gen_alias_sets - 06/14/93
#
#-----------------------------------------------------------------------------
#

outfile="$1"

{
  $GREP -v '^#' /etc/aliases |
  $SORT > $WORKDIR/etc_aliases.$$
  echo "/etc/aliases" > $WORKDIR/etc_aliases.$$.src
  echo $WORKDIR/etc_aliases.$$

  [ -n "$YP" ] && {
    $YPCAT -k aliases |
    $SED -e 's/ /:/' | 
    $SORT |
    $COMM -23 - $WORKDIR/etc_aliases.$$ > $WORKDIR/nis_aliases.$$
    echo "NIS" > $WORKDIR/nis_aliases.$$.src
    echo $WORKDIR/nis_aliases.$$
  }
} > $outfile
