#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# AIX/3/gen_export_sets - 06/14/93
#
#-----------------------------------------------------------------------------
#

[ -r /etc/exports ] && {
  $GREP -v '^#' /etc/exports > $WORKDIR/etc_exports.$$
  echo "/etc/exports" > $WORKDIR/etc_exports.$$.src
  echo $WORKDIR/etc_exports.$$
}
