#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# NeXT/3/gen_cron - 06/14/93
#
#-----------------------------------------------------------------------------
#

cronfiles=
[ -f /private/etc/crontab ] &&
  cronfiles="$cronfiles /private/etc/crontab"
[ -f /private/etc/crontab.local ] &&
  cronfiles="$cronfiles /private/etc/crontab.local"

[ -n "$cronfiles" ] && {
  $AWK '
    for(i=6;i<=NF;i++)
      printf("%s ", $i);
    printf("\n");
  ' $cronfiles
}
