#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# AIX/3/gen_services - 06/14/93
#
#-----------------------------------------------------------------------------
#

$GREP -v '^#' /etc/services > $WORKDIR/etc_services.$$
echo "/etc/services" > $WORKDIR/etc_services.$$.src
echo $WORKDIR/etc_services.$$

[ -n "$YP" ] && {
  $YPCAT services > $WORKDIR/nis_services.$$
  echo "NIS" > $WORKDIR/nis_services.$$.src
  echo $WORKDIR/nis_services.$$
}

