#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# getdisks - 06/24/93
#
#-----------------------------------------------------------------------------
#

/etc/mount |
$AWK '$5 == "4.3" {print}' |
$SORT |
$AWK '
  BEGIN {lastdisk=""; fslist="";}
  {
    disk=substr($1, 1, length($1)-1);
    if(disk == lastdisk){
       fslist=fslist " " $3;
    }
    else {
	if(lastdisk != ""){
           printf("%s\n", fslist);
        }
        lastdisk=disk;
        fslist = $3;
    }
  }
  END { if(lastdisk != ""){
          printf("%s\n", fslist);
        } 
  }'

