#!/bin/sh
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#
# cd to / in case we are down in a directory we don't have read
# access to.  /bin/csh will barf if that is the case.
#
cd /

user="$1"

/bin/csh -c "echo ~$user" 2> /dev/null


