#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_lilo:  checks permissions on boot loader config files
#		grub.conf and lilo.conf
# 10.26.2001
# Paul Telford <paul_telford@hp.com>
# 04.25.2002  Javier Fernandez-Sanguino <jfs@computer.org>
# Expanded to check also if there are passwords in the boot loader
# 07/25/2002 jfs       
# Changed TigerInstallDir to .
# Changed -e to -r and 'find' to 'access' in the error msg.
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done
#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}
. $basedir/config

. $BASEDIR/initdefs
#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds AWK CAT COMM GEN_INETD_SETS GEN_SERVICES_SETS GREP JOIN LS RM SORT TAIL UNIQ || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}
#------------------------------------------------------------------------
haveallcmds AWK CAT COMM GEN_INETD_SETS GEN_SERVICES_SETS GREP JOIN LS RM SORT TAIL UNIQ || exit 1
haveallfiles BASEDIR WORKDIR || exit 1
echo
echo "# Checking boot loader file permissions..."
found="N"

file=/etc/lilo.conf
if [ -r $file ]
then

	found="Y"
	getpermit $file |
	   while read filename rowner rgroup rur ruw rux rgr rgw rgx ror row rox rsuid rsgid rstk
	do

	if [ $rgr -eq 1 -o $rgw -eq 1 -o $rgx -eq 1 ]
	then
                message WARN boot01 "" "The configuration file lilo.conf has group permissions"
	fi
	if [ $ror -eq 1 -o $row -eq 1 -o $rox -eq 1 ]
	then
                message FAIL boot01 "" "The configuration file lilo.conf has other permissions"
        fi

	done

	# Lilo password checks
	if [ -n "`$GREP ^restricted $file`" ] ; then
            if [ -z "`$GREP ^password $file`" ] ; then
                message WARN boot05 "" "The bootloader is restricted but does not seem to have a password configured."
	    fi 
	else
                message WARN boot04 "" "The bootloader lilo is not configured with a password"
	fi

fi

file=/boot/grub/grub.conf
if [ -r $file ]
then

	found="Y"
	getpermit $file |
	   while read filename rowner rgroup rur ruw rux rgr rgw rgx ror row rox rsuid rsgid rstk
	do

	if [ $rgr -eq 1 -o $rgw -eq 1 -o $rgx -eq 1 ]
	then
                message WARN boot02 "" "The configuration file grub.conf has group permissions.  Should be 0600"
	fi
	if [ $ror -eq 1 -o $row -eq 1 -o $rox -eq 1 ]
	then
                message FAIL boot02 "" "The configuration file grub.conf has world permissions.  Should be 0600"
        fi

	done
	# GRUB password checks
        if [ -z "`$GREP ^password $file`" ] ; then
                message WARN boot06 "" "The Grub bootloader does not have a password configured."
	fi 
fi

[ "$found" != 'Y' ] && {
	message WARN boot03 "" "Could not access lilo.conf or grub.conf"
}
