#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_single: looks for 'sulogin' line in /etc/inittab which would
# 		indicate a password requirement on single user mode
# 10.26.2001
# Paul Telford <paul_telford@hp.com>
# 07/25/2002 jfs      Changed -e lilo.conf to -r lilo.conf
#                     Changed TigerInstallDir to .
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done
#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}
. $basedir/config

. $BASEDIR/initdefs
#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds AWK CAT COMM GEN_INETD_SETS GEN_SERVICES_SETS GREP JOIN LS RM SORT TAIL UNIQ || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}
#------------------------------------------------------------------------

echo
echo "# Checking for single user-mode password..."
haveallcmds AWK CAT COMM GEN_INETD_SETS GEN_SERVICES_SETS GREP JOIN LS RM SORT TAIL UNIQ || exit 1
haveallfiles BASEDIR WORKDIR || exit 1

# if we find a boot-loader password, great. 
# If not, look for single-user mode password in inittab 

if [ -r /etc/lilo.conf ]
then
	$GREP "password=" /etc/lilo.conf 1> /dev/null
	if [ $? -eq 0 ]
	then
		exit 0
	fi
elif [ -e /boot/grub/menu.lst ]
then
	$GREP "password" /boot/grub/menu.lst 1> /dev/null
	if [ $? -eq 0 ]
	then
		exit 0
	fi
else		
	SULOGIN_STRING="~~:S:wait:/sbin/sulogin"
	$GREP "$SULOGIN_STRING" /etc/inittab 1> /dev/null
	if [ $? -eq 1 ]
	then
		message FAIL sum001 "" "Recommend addition to /etc/inittab:  $SULOGIN_STRING"
	fi
fi
