#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_release: verifies that system meets minimum release requirements
# 10.26.2001
# Paul Telford <paul_telford@hp.com>
# 07/25/2002 jfs       Changed TigerInstallDir to .
# 10/01/2003 jfs       Fixed message calls
# 11/09/2003 jfs       Removed typeset bashism and updated RedHat versions so
#            only 7.1 or greater are consider current (Debian Bug 219764)
# 01/15/2004 jfs       Updated RedHat version (now it's 9 or greater), but
#            added a note regarding Progeny support...
# 03/21/2005 jfs       Use EGREP instead of grep -E
#
#-----------------------------------------------------------------------------
# TODO:
# - Support more distributions (SuSE, Mandrake...)
# - Add support to RedHat Enterprise distributions?
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done
#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}
. $basedir/config

. $BASEDIR/initdefs
#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds CUT EGREP RM  || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}
#------------------------------------------------------------------------

echo
echo "# Checking OS release..."
haveallcmds CUT EGREP RM  || exit 1
haveallfiles BASEDIR WORKDIR || exit 1

if [ -e /etc/redhat-release ]
then
        REDHAT_VERSION=`$CUT -f5 -d' ' /etc/redhat-release`
        $EGREP "[A-Za-z]" $REDHAT_VERSION 1> /dev/null
	if [ $? -eq 1 ]
	then
		MAJOR=`echo $REDHAT_VERSION | $CUT -d. -f1`
		MINOR=`echo $REDHAT_VERSION | $CUT -d. -f2`
		# Note: RedHat 9 EOL is April 30th, 2004.
		# Also notice that Progeny does provide official support
		# for 7.2, 7.3, 8.0 and 9.0 starting January 1, 2004
		# (but only for x86) see http://transition.progeny.com/
		if [ $MAJOR -lt 9 ]
		then
			message FAIL osv001f "" "Out of date Redhat Linux version $REDHAT_VERSION"

#		elif [ $MAJOR -eq X -a $MINOR -lt X ]
#	        then
#	       	         message FAIL osv001f "" "Out of date Redhat Linux version $REDHAT_VERSION"
#       		         return
       		 fi
	else
                 message WARN osv004w "" "Unreleased RedHat Linux version \`$REDHAT_VERSION'"
	fi
	
# Debian seems to put either a number or a codename in their
# version file so we have to check for both.
elif [ -e /etc/debian_version ]
then
	# these are the codenames for the older debian releases
	# if we see any of them we know we fail right away
        DEBIAN_VERSION=`$CUT -f1 -d' ' /etc/debian_version`
        $EGREP "hamm|bo|rex|buzz" /etc/debian_version 2> /dev/null
        if [ $? -eq 0 ]
        then
                message FAIL osv002f "" "Out of date Debian GNU/Linux version"
        else
            $CUT -f1 -d' ' /etc/debian_version | $EGREP "[A-Za-z]" 1> /dev/null
            if [ $? -eq 1 ]
            then
                MAJOR=`echo $DEBIAN_VERSION | $CUT -d \. -f 1`
                MINOR=`echo $DEBIAN_VERSION | $CUT -d \. -f 2`
                if [ "$MAJOR" -lt 3 ]
                then
                        message FAIL osv002f "" "Out of date Debian GNU/Linux version \`$DEBIAN_VERSION'"
                elif [ "$MAJOR" -eq 3 -a "$MINOR" -lt 0 ]
                then
                        message FAIL osv002f "" "Out of date Debian GNU/Linux version \`$DEBIAN_VERSION'"
                fi
            else
                        message WARN osv004w "" "Unreleased Debian GNU/Linux version \`$DEBIAN_VERSION'"
	     fi
	    
        fi
else
        message WARN osv003w "" "This check only works for Redhat and Debian"
fi
 
