#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 2002 Javier Fernandez-Sanguino Pen~a
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_rcumask - Sat May 18 17:50:00 CEST 2002
#
# check_rcumask - 05/21/2009 - jfs - Remove shell login umasks and add Debian's /etc/init.d/rc.
#                                    Adjust haveallcmds definition
# check_rcumask - 06/23/2007 - jfs - Fix syntax error (Debian bug #430224)
# check_rcumask - 06/21/2007 - jfs - Skip comment lines (Debian bug #418531)
# check_rcumask - 05/20/2006 - jfs - Use TAIL properly (POSIX 1003.2-1992)
# check_rcumask - 10/15/2004 - jfs - Proper warning if no umask settings
#       are defined (Debian bug #234661)
# check_rcumask - 10/15/2003 - jfs - Removed bashishm (Debian bug #215896)
# check_rcumask - 07/25/2002 - jfs
#       Changed TigerInstallDir to .
# check_rcumask - 09/10/2002 - jfs
#	Fixed to work in sh properly (and added necessary checks)
# check_rcumask - 08/09/2003 - jfs
#       Included patch to check for more source files
#
# Checks if there is a umask setting for the init.d scripts (rc) so that
# the init scripts create files with a proper mode (umask 022 so that files
# are created at least with 0644 permissions).
#
# Done based on scripts/check_logfiles (since the code to look for umasks
# is there already). The code is included only on Linux scripts since it
# has not been tested in other environments.
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds  HEAD TAIL GREP EXPAND SED CUT || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  haveallvars TESTLINK HOSTNAME
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------

echo
echo "# Checking for correct umask settings for init scripts..."

haveallcmds HEAD TAIL GREP EXPAND SED CUT  || exit 1


#####
# Check various possible files
#####

Foundumask=0

# Files include Debian's rc and rcS, Titan's umask.sh file and Red Hat default 
# source for initscripts: /etc/rc.d/init.d/functions
for file in '/etc/init.d/rcS' '/etc/rc.d/init.d/umask.sh' '/etc/init.d/umask.sh' '/etc/rc.d/init.d/functions' '/etc/init.d/rc'
do
   [ -r $file ] && {

   Occurance=`$GREP umask $file |$GREP -v ^# | $WC -l`

   if [ $Occurance -eq 1 ]; then
	Foundumask=1
	UMASK1=`$GREP umask $file  \
           | $GREP -v ^\# \
           | $EXPAND  \
           | $SED -e "s/^.*umask//"\
           | $CUT -d" " -f2`

	[ "$UMASK1" != "002" -a "$UMASK1" != "022" ] && 
		message FAIL misc017f '' "The umask setting in $file for the init scripts is insecure"


    elif [ "$Occurance" = 2 ]; then
	Foundumask=1
	UMASK1=`$GREP umask $file  \
             | $GREP -v ^# \
             | $EXPAND \
             | $HEAD -n 1 \
             | $SED -e "s/^.*umask//" \
             | $CUT -d" "  -f2`
	UMASK2=`$GREP umask $file  \
             | $GREP -v ^# \
             | $EXPAND \
             | $TAIL -n 1 \
             | $SED -e "s/^.*umask//" \
             | $CUT -d" "  -f2`

 	[ "$UMASK1" != "002" -a "$UMASK1" != "022" -o "$UMASK2" != "002" -a "$UMASK2" != "022" ] &&
		message FAIL misc017f '' "The umask setting in $file for the init scripts is insecure"
        elif [ "$Occurance" = 0 ]; then
	        message WARN misc021w "" "There are no umask entries in $file"
	else
		message WARN misc018w '' "There are more than 2 umask entries in $file"

fi

}

done

if [ "$Foundumask" -eq 0 ]; then
	message WARN misc019w "" "There are no umask settings for init.d scripts"
fi
