#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 2002 Javier Fernandez-Sanguino Pen~a
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_rcumask - Sat May 18 17:50:00 CEST 2002
#
# check_rcumask - 07/25/2002 - jfs
#       Changed TigerInstallDir to .
# check_rcumask - 09/10/2002 - jfs
#	Fixed to work in sh properly (and added necessary checks)
#
# Checks if there is a umask setting for the init.d scripts (rc) so that
# these create files with a proper mode (644).
# Done based on scripts/check_logfiles (since the code to look for umasks
# is there already). The code is included only on Linux scripts since it
# has not been tested in other environments.
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds  HEAD TAIL GREP EXPAND SED CAT SORT AWK LS RM || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  haveallvars TESTLINK HOSTNAME
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------

echo
echo "# Checking for correct umask settings for init scripts..."

haveallcmds HEAD TAIL GREP EXPAND SED CAT SORT LS AWK || exit 1


#####
# Check various possible files
#####

Foundumask=0

# Files include Debian's rcS and Titan's umask.sh file
for file in '/etc/init.d/rcS' '/etc/rc.d/init.d/umask.sh' '/etc/init.d/umask.sh'
do
   [ -r $file ] && {

   Occurance=`$GREP umask $file | $WC -l`

   if [ $Occurance -eq 1 ]; then
	Foundumask=1
	UMASK1=`$GREP umask $file  \
           | $EXPAND  \
           | $SED -e "s/^.*umask//"\
           | $CUT -d" " -f2`

	[ $UMASK1 != 002 -a $UMASK1 != 022 ] && 
		message FAIL misc017f '' "The umask setting in $file for the init scripts is insecure"


    elif [ $Occurance == 2 ]; then
	Foundumask=1
	UMASK1=`$GREP umask $file  \
             | $EXPAND \
             | $HEAD -n 1 \
             | $SED -e "s/^.*umask//" \
             | $CUT -d" "  -f2`
	UMASK2=`$GREP umask $file  \
             | $EXPAND \
             | $TAIL -n 1 \
             | $SED -e "s/^.*umask//" \
             | $CUT -d" "  -f2`

 	[ $UMASK1 != 002 -a $UMASK1 != 022 -o $UMASK2 != 002 -a $UMASK2 != 022 ] &&
		message FAIL misc017f '' "The umask setting in $file for the init scripts is insecure"
	else
		message WARN misc018w '' "There are more than 2 umask entries in $file"

fi

}

done

if [ $Foundumask -eq 0 ]; then
	message WARN misc019w "" "There are no umask settings for init.d scripts"
fi
