#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# SunOS/4/gen_bootparam_sets - 06/14/93
#
#-----------------------------------------------------------------------------
#

[ -r /etc/bootparams ] && {
  $SED -e 's/#.*$//' /etc/bootparams |
  $SED -e '/^[ \t]*$/d' |
  $AWK '
       BEGIN {LINE="";}
       /\\\\$/ {LINE=LINE " " substr($0, 1, length($0)-1);}
       !/\\\\$/ {print LINE $0; LINE="";}
  ' > $WORKDIR/etc_bootparams.$$
  echo "/etc/bootparams" > $WORKDIR/etc_bootparams.$$.src
  echo "$WORKDIR/etc_bootparams.$$"
}

[ -n "$YP" ] && {
  $YPCAT bootparams > $WORKDIR/nis_bootparams.$$
  echo "NIS" > $WORKDIR/nis_bootparams.$$.src
  echo "$WORKDIR/nis_bootparams.$$"
}
