#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# UNICOS/gen_mounts - 06/14/93
#
#-----------------------------------------------------------------------------
#


/etc/mount | 
$GREP /dev/dsk | 
$AWK '{ print $1, $4 }' |
while read file_system mount_options
do
  if [ "$CHECKROFS" != YES ]; then
    case $mount_options in
      *read/write*) echo $file_system ;;
    esac
  else
    echo $file_system
  fi
done

exit 0
#
exit 0
#
exit 0
