#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# sub/check_links - 06/14/93
#
#-----------------------------------------------------------------------------
# This script is not runnable directly.
# 
file="$1"

[ "$CONFIGURED_ALREADY" != "YES" ] && {
  echo "--ERROR-- [init008e] This script can not be run directly."
  exit 1
}

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds SORT GREP JOIN LS CAT CC RM || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------
echo
echo "# Checking symbolic links..."

haveallcmds SORT GREP JOIN LS REALPATH || exit 1
haveallfiles WORKDIR || exit 1

$REALPATH < $file |
$SORT +1 > $WORKDIR/link.tmp.$$

$GREP -v '^#' $FILE_ACL |
$SORT |
$JOIN -j2 2 -o 2.1 2.2 1.1 - $WORKDIR/link.tmp.$$ |
while read file realfile facl
do
  $LS -ld $LSGROUP "$file" | {
    read p l owner group s a b c f
    [ "$owner" != 'root' -a "$owner" != 'bin' ] && {
      echo "--INFO-- [fsys007i] Symbolic link \`$file' points to \`$realfile'."
    }
  }
done

delete $WORKDIR/link.tmp.$$

