#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_trusted: Verifies the system is running in trusted mode.
# For more information on trusted mode in HP-UX please read
# http://docs.hp.com/hpux/onlinedocs/B2355-90121/B2355-90121.html 
# Tested on HP-UX 11.11, HP-UX 11.00, and HP-UX 10.20.
#
# 06/25/2003 rbradetich@uswest.net - Initial release
# 06/26/2003 jfs - Added a TODO item, added a check to see if GETPRDEF is
#                  available.
# 08/09/2003 jfs - Patch from Ryan Bradetich which adds a check to determine
#                  system will lock accounts after a number of failed attempts.
# 23/05/2010 Francisco G. Claramonte - Fixed a bashism problem with
#                  logical expression, added '$' in '((..))' expression.
#
#-----------------------------------------------------------------------------
# TODO:
# - HP documentation says that only HP-UX Release 10.10 and later support
# enabling trusted mode. Consider including a check to determine we
# are not in an _ancient_ system
#
# - This check can be improved in the future to possibly specify the 
#   number of failed login attempts, etc.
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}
. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallfiles BASEDIR || exit 1
  haveallcmds GETPRDEF || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}
#------------------------------------------------------------------------
haveallfiles BASEDIR || exit 1
haveallcmds GETPRDEF || exit 1

echo
echo "# Verifying trusted mode..."

$GETPRDEF -r 2>&1 >/dev/null
if [ $? -eq 4 ]; then
  message WARN trust001w "" "The system is not running in trusted mode."
  exit 0
fi

# Verify the number of login attempts are limited.
num=`$GETPRDEF -m umaxlntr`
( [ -z "$num" ] || $(( ${num#umaxlntr=} < 1 ))) && {
  message WARN trust002w "" "The system is not configured to limit the number of login attempts."
}

exit 0
