#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# HPUX/check - 06/25/2003
# 
# Checks for HPUX systems.
# 
# 06/25/2003 - rbradetich@uswest.net - Initial version
# 06/26/2003 - jfs - Moved the definition of the configuration variable to
#              tigerrc and capitalise it.
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallfiles BASEDIR WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------

haveallfiles BASEDIR WORKDIR || exit 1

SYSTEMDIR=$BASEDIR/systems/HPUX
#
# The following scripts have been added to provide platform
# specific checks for HP-UX.  This script was modified from
# the systems/Linux/2/check script.
# 

# Verify the system is running in trusted mode.
[ "$Tiger_Check_TRUSTED" = 'Y' ] && {
  $SYSTEMDIR/check_trusted
}

# Perform system specific password checks.
[ "$Tiger_Check_PASSWD" != 'N' ] && {
  $SYSTEMDIR/check_passwdspec
}
