#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_trusted: Verifies the system is running in trusted mode.
# For more information on trusted mode in HP-UX please read
# http://docs.hp.com/hpux/onlinedocs/B2355-90121/B2355-90121.html 
#
# 06/25/2003 rbradetich@uswest.net - Initial release
# 06/26/2003 jfs - Added a TODO item
#
#-----------------------------------------------------------------------------
# TODO:
# HP documentation says that only HP-UX Release 10.10 and later support
# enabling trusted mode. Consider including a check to determine we
# are not in an _ancient_ system
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}
. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallfiles BASEDIR WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}
#------------------------------------------------------------------------
haveallfiles BASEDIR WORKDIR || exit 1

echo
echo "# Verifying trusted mode..."

/usr/lbin/getprdef -r 2>&1 >/dev/null
if [ $? -eq 4 ]; then
  message WARN trust001w "" "The system is not running in trusted mode."
fi
