#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# HPUX/gen_alias_sets - 06/14/93
#
#-----------------------------------------------------------------------------
#

aliasfile=`$GREP '^A' /usr/lib/sendmail.cf 2>/dev/null | $SED -e 's/^.//'`

[ ! -n "$aliasfile" ] && aliasfile=/usr/lib/aliases

[ -r $aliasfile ] && {
  $GREP -v '^#' $aliasfile |
  $SORT > $WORKDIR/etc_aliases.$$
  echo "$aliasfile" > $WORKDIR/etc_aliases.$$.src
  echo $WORKDIR/etc_aliases.$$
}

[ -n "$YP" ] && {
  $YPCAT -k aliases 2>/dev/null >/dev/null && {
    $YPCAT -k aliases |
    $SED -e 's/ /:/' | 
    $SORT |
    $COMM -23 - $WORKDIR/etc_aliases.$$ > $WORKDIR/nis_aliases.$$
    echo "NIS" > $WORKDIR/nis_aliases.$$.src
    echo $WORKDIR/nis_aliases.$$
  }
}
