#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# HPUX/genexports - 06/14/93
#
#-----------------------------------------------------------------------------
#

[ -r /etc/exports ] && {
  $SED -e 's/#.*$//' -e '/^$/d' /etc/exports |
  while read dir options
  do
    sep=
    hsep=
    optstr=
    hostlist=
    for opt in $options
    do
      case $opt in
	-*) optstr="$optstr$sep`echo $opt | $SED -e 's/^-//'`"; sep=",";;
	*) hostlist="$hostlist$hsep$opt";hsep=":";;
      esac
    done
    [ -n "$hostlist" ] && hostlist="-access=$hostlist"
    [ ! -n "$hostlist" -a -n "$optstr" ] && optstr="-$optstr"
    sep=
    [ -n "$hostlist" -a -n "$optstr" ] && sep=","
    echo "$dir $hostlist$sep$optstr"
  done > $WORKDIR/etc_exports.$$
  echo "/etc/exports" > $WORKDIR/etc_exports.$$.src
  echo $WORKDIR/etc_exports.$$
}
