#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# SunOS/5/gen_inetd - 06/14/93
#
#-----------------------------------------------------------------------------
#

[ ! -h /etc/inetd.conf -a -r /etc/inetd.conf ] && {
  $GREP -v '^#' /etc/inetd.conf |
  $SORT > $WORKDIR/etc_inetd.$$
  echo "/etc/inetd.conf" > $WORKDIR/etc_inetd.$$.src
  echo $WORKDIR/etc_inetd.$$
}

[ -r /etc/inet/inetd.conf ] && {
  $GREP -v '^#' /etc/inet/inetd.conf |
  $SORT > $WORKDIR/etc_inetd2.$$
  echo "/etc/inet/inetd.conf" > $WORKDIR/etc_inetd2.$$.src
  echo $WORKDIR/etc_inetd2.$$
}
  
