#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# SunOS/4/gen_export_sets - 06/14/93
#
# TODO:
#
# - This will not work for SunOS versions later than 5.5
#   /etc/exports has been moved
#   to /etc/dfs/dfstab (see share_nfs(1M) and nfssec(5)
#  see  http://docs.sun.com/db/doc/802-1967/6i5vce4fu
#
#-----------------------------------------------------------------------------
#

[ -r /etc/exports ] && {
  $GREP -v '^#' /etc/exports > $WORKDIR/etc_exports.$$
  echo "/etc/exports" > $WORKDIR/etc_exports.$$.src
  echo $WORKDIR/etc_exports.$$
}
