#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# buildbins - 06/16/93
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

outfile=
[ -n "$1" ] && {
  case "$1" in
    -*);;
    *) outfile="$1"; shift;;
  esac
}

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

TigerNoBuild=Y

. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds RM CC CAT MV  || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------

haveallcmds CAT || exit 1
haveallfiles BASEDIR BINDIR WORKDIR || exit 1

snefru="snefru.c"
realpath="realpath.c"
testsuid="testsuid.c"
md5="md5.c"
getpermit="getpermit.c"

toplevel=$BASEDIR/systems/$OS

setbintype=0
if [ -f $BINDIR/.bintype ]; then
  read os rev arch < $BINDIR/.bintype
  [ "$os" != "$OS" -o "$rev" != "$REV" -o "$arch" != "$ARCH" ] && {
    for file in $cmds
    do
      $RM -f $BINDIR/$file
    done
    $RM -f $BINDIR/.bintype
    setbintype=1
  }
else
  setbintype=1
fi

{
  while read cmd cmdvar
  do
    foundit=0
    for dir in $REL/$REV/$ARCH $REL/$REV $REL
    do
      if [ $TESTEXEC $toplevel/$dir/$cmd ]; then
	echo "$cmdvar=$toplevel/$dir/$cmd; export $cmdvar"
	foundit=1
	break
      fi
    done

    [ $foundit -eq 0 ] &&
    if [ $setbintype -eq 1 -o ! $TESTEXEC $BINDIR/$cmd ]; then
      haveallcmds CC && {
	eval sources="\$$cmd"
	objlist=
	for source in $sources
	do
	  foundit=0
	  
	  for dir in $REL/$REV/$ARCH $REL/$REV $REL
	  do
	    if [ -f $toplevel/$dir/$source ]; then
	      $CAT $toplevel/$dir/$source > $WORKDIR/$source
	      (cd $WORKDIR; $CC $CFLAGS -c $source)
	      delete $WORKDIR/$source
	      foundit=1
	      break
	    fi
	  done
	  
	  [ $foundit -ne 1 -a -f $BASEDIR/c/$source ] && {
	    $CAT $BASEDIR/c/$source > $WORKDIR/$source
	    (cd $WORKDIR; $CC $CFLAGS -c $source)
	    delete $WORKDIR/$source
	    foundit=1
	  }
	
	  [ $foundit -eq 1 ] && {
	    objlist="$objlist `$BASENAME $source .c`.o"
	  }
	done
      
	(
          umask 022
	  cd $WORKDIR
	  $CC $CFLAGS $objlist -o $cmd $CLIBS
	)
	if [ -f $WORKDIR/$cmd ]; then
	  (
	    umask 022
	    if haveallcmds MV; then
	      $MV $WORKDIR/$cmd $BINDIR 2>/dev/null &&
	        echo "$cmdvar=$BINDIR/$cmd; export $cmdvar"
	    else
	      $CAT $WORKDIR/$cmd > $BINDIR/$cmd 2>/dev/null &&
		echo "$cmdvar=$BINDIR/$cmd; export $cmdvar"
	      delete $WORKDIR/$cmd
	    fi
	    if [ -f $WORKDIR/$cmd ]; then
	      # For some reason it didn't move... use it where it sits
	      # We won't be cleaning this up though... sorry...
	      echo "$cmdvar=$WORKDIR/$cmd; export $cmdvar"
	    fi
	  )
	fi
	for obj in $objlist
	do
	  delete $WORKDIR/$obj
	done
      }
    else
      echo "$cmdvar=$BINDIR/$cmd; export $cmdvar"
    fi
  done << EOF
realpath REALPATH
snefru SNEFRU
testsuid TESTSUID
md5 MD5
getpermit GETPERMIT
EOF
} |
{
  if [ -n "$outfile" ]; then
    $SED -e 's/^\(--[A-Z].*\)$/echo "\1"/' > $outfile
  else
    $SED -e 's/^\(--[A-Z].*\)$/echo "\1"/'
  fi
}

[ $setbintype -eq 1 ] && {
  echo "$OS $REV $ARCH" > $BINDIR/.bintype
  haveallcmds CHMOD && $CHMOD 644 $BINDIR/.bintype
} 2>/dev/null
