#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# util/logit - 04/22/93
#
#-----------------------------------------------------------------------------
# Lovely eh?

# Unduly complicated so that we can get rid of any nasty newlines
# (they are converted to ~'s).

{
  echo "$2" |
  $AWK '
    BEGIN {lc="";}
    {
      printf("%s%s", lc, $0);
      lc="~";
    }
  '
  echo
} >> $1
