#!/bin/sh -e

. /usr/share/debconf/confmodule

db_input medium tiger/mail_rcpt || true
db_input medium tiger/policy_adapt || true
# Only ask for it if necessary
cruft=`find /var/log/ -type f -maxdepth 1 -name "tiger*"`
if [ ! -z "$cruft" ] ; then
	db_input low tiger/remove_mess || true
fi
db_go

