#!/bin/sh -e

# System configuration file:
CONFIG=/etc/tiger/tigerrc
# Package-provided configuration file:
PKGCONFIG=/usr/share/tiger/tigerrc

test $DEBIAN_SCRIPT_DEBUG && set -v -x

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see /usr/doc/packaging-manual/
#
# quoting from the policy:
#     Any necessary prompting should almost always be confined to the
#     post-installation script, and should be protected with a conditional
#     so that unnecessary prompting doesn't happen if a package's
#     installation fails and the `postinst' is called with `abort-upgrade',
#     `abort-remove' or `abort-deconfigure'.

case "$1" in
    install)
    ;;
    upgrade)
    ;;
    configure)
	# Obtain the configured value
        . /usr/share/debconf/confmodule
	db_get tiger/mail_rcpt || true
        MAIL_RCPT="$RET"

        # Create temporary file for use in UCF
        tempfile=`tempfile` || { echo "Cannot create temporary file, aborting" >&2; exit 1; }

        # Determine if we are using a compressed configuration file or not
        CAT=cat
        if echo $PKGCONFIG | grep -q .gz; then
            CAT=zcat
        fi
        if [ ! -e "$PKGCONFIG" ] ; then
            echo "ERROR in maintainer script, cannot find package configuration file at $PKGCONFIG" >&2
            exit 1
        fi
        $CAT $PKGCONFIG | sed -e "s/^Tiger_Mail_RCPT=.*$/Tiger_Mail_RCPT=\"$MAIL_RCPT\"/"  > $tempfile

        # Use UCF to handle file changes
        ucf --debconf-ok $tempfile $CONFIG
        ucfr tiger $CONFIG
        rm -f $tempfile
    ;;
    abort-upgrade)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac


#DEBHELPER#

exit 0
