#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#     Copyright (C) 2004 Ryan Bradetich
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# Tru64/5/gen_inetd - 04/01/2004
#
#-----------------------------------------------------------------------------
# TODO: Tru64 has /etc/inetd.conf.local file to deal with as well.

$GREP -v '^#' /etc/inetd.conf |
$SORT > $WORKDIR/etc_inetd.$$
echo "/etc/inetd.conf" > $WORKDIR/etc_inetd.$$.src
echo $WORKDIR/etc_inetd.$$
