#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# NeXT/3/gen_bootparam_sets - 06/14/93
#
#-----------------------------------------------------------------------------
#

COUNT=1

/usr/etc/nidomain -l | 
$AWK '{ print substr($1,5,length($1) - 4) }' |
{
  while read NETINFO_TAG
  do
    BOOTPARAM_SET=$WORKDIR/bootparam.set$COUNT.$$

    /usr/bin/nidump -t bootparams localhost/$NETINFO_TAG |
    $SED -e 's/#.*$//' |
    $SED -e '/^[ \t]*$/d' |
    $AWK '
	 BEGIN {LINE="";}
	 /\\\\$/ {LINE=LINE " " substr($0, 1, length($0)-1);}
	!/\\\\$/ {print LINE $0; LINE="";}
    ' > $BOOTPARAM_SET

    echo "NetInfo($NETINFO_TAG)" > $BOOTPARAM_SET.src
    echo $BOOTPARAM_SET
    COUNT=`$EXPR $COUNT + 1`
  done
}

[ -n "$YP" ] && {
  BOOTPARAM_SET=$WORKDIR/bootparam.set.nis.$$
  $YPCAT bootparams > $BOOTPARAM_SET
  echo "NIS" > $BOOTPARAM_SET.src
  echo $BOOTPARAM_SET
}

[ -r /etc/bootparams ] && {
  BOOTPARAM_SET=$WORKDIR/bootparam.set.etc.$$
  $CAT /etc/bootparams |
  $SED -e 's/#.*$//' |
  $SED -e '/^[ \t]*$/d' > $BOOTPARAM_SET

  echo "/etc/bootparams" > $BOOTPARAM_SET.src
  echo $BOOTPARAM_SET
}
