#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# NeXT/3/gen_group_sets - 06/14/93
#
#-----------------------------------------------------------------------------
#

$GREP -v '^[-+#]' /etc/group |
$SORT > $WORKDIR/etc_group.$$
echo "/etc/group" > $WORKDIR/etc_group.$$.src
echo $WORKDIR/etc_group.$$

COUNT=1

/usr/etc/nidomain -l | 
$AWK '{ print substr($1,5,length($1) - 4) }' | (
    while read NETINFO_TAG
    do
	GROUP_SET=$WORKDIR/group.set$COUNT.$$
	/usr/bin/nidump -t group localhost/$NETINFO_TAG > $GROUP_SET
	echo "NetInfo($NETINFO_TAG)" > $GROUP_SET.src
	echo $GROUP_SET
	COUNT=`$EXPR $COUNT + 1`
    done
    exit $COUNT
)

[ -n "$YP" ] && {
  $YPCAT group |
  $SORT |
  $COMM -23 - $WORKDIR/etc_group.$$ > $WORKDIR/nis_group.$$
  echo "NIS" > $WORKDIR/nis_group.$$.src
  echo $WORKDIR/nis_group.$$
}
