#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# NeXT/3/gen_cron - 06/14/93
#
#-----------------------------------------------------------------------------
#

cronfiles=
[ -f /private/etc/crontab ] &&
  cronfiles="$cronfiles /private/etc/crontab"
[ -f /private/etc/crontab.local ] &&
  cronfiles="$cronfiles /private/etc/crontab.local"

[ -n "$cronfiles" ] && {
  $AWK '
    for(i=6;i<=NF;i++)
      printf("%s ", $i);
    printf("\n");
  ' $cronfiles
}
