#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# NeXT/3/gen_services - 06/14/93
#
#-----------------------------------------------------------------------------
#

COUNT=1

/usr/etc/nidomain -l | 
$AWK '{ print substr($1,5,length($1) - 4) }' | (
    while read NETINFO_TAG
    do
        SERVICES_SET=$WORKDIR/services.set$COUNT.$$
        /usr/bin/nidump -t services localhost/$NETINFO_TAG > $SERVICES_SET
        echo "NetInfo($NETINFO_TAG)" > $SERVICES_SET.src
        echo $SERVICES_SET
        COUNT=`$EXPR $COUNT + 1`
    done
    exit $COUNT
)

COUNT=$?

[ -n "$YP" ] && {
    SERVICES_SET=$WORKDIR/services.set$COUNT.$$
    $YPCAT services > $SERVICES_SET
    echo "NIS" > $SERVICES_SET.src
    echo $SERVICES_SET
    COUNT=`$EXPR $COUNT + 1`
}

SERVICES_SET=$WORKDIR/services.set$COUNT.$$
$GREP -v '^#' /etc/services > $SERVICES_SET
echo "/etc/services" > $SERVICES_SET.src
echo $SERVICES_SET
