#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# IRIX/4/gen_group_sets - 06/14/93
#
#-----------------------------------------------------------------------------
#

$GREP -v '^[-+]' /etc/group |
$SORT > $WORKDIR/etc_group.$$
echo "/etc/group" > $WORKDIR/etc_group.$$.src
echo $WORKDIR/etc_group.$$

[ -n "$YP" ] && {
  $YPCAT group |
  $SORT |
  $COMM -23 - $WORKDIR/etc_group.$$ > $WORKDIR/nis_group.$$
  echo "NIS" > $WORKDIR/nis_group.$$.src
  echo $WORKDIR/nis_group.$$
}

