#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_devices
# 	checks permissions on tape devices
# 10-30-2001
# Paul Telford <paul_telford@hp.com>
#
# 07/25/2002 jfs  Changed TigerInstallDir to .
# 08/09/2002 jfs  Fixed to work in Solaris (added pseudo devices and changed
#                 -L to -h)
# 08/12/2002 jfs  Added /devices/pseudo/pts to terminal lists.
# 04/15/2003 jfs  Fixed stupid error which made terminals appear 
#		  (/dev/ -> /dev)
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done
#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}
. $basedir/config

. $BASEDIR/initdefs
#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds AWK CAT COMM GEN_INETD_SETS GEN_SERVICES_SETS GREP JOIN LS RM SORT TAIL UNIQ || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}
#------------------------------------------------------------------------

check_dev_file()
{
	device=$1
	getpermit $device |
    	while read filename rowner rgroup rur ruw rux rgr rgw rgx ror row rox rsuid rsgid rstk
    	do
		if [ $ror -eq 1 -o $row -eq 1 -o $rox -eq 1 ]
		then
		case $device in
		/dev/st[0-9])
			message FAIL dev001 "" "$device has world permissions"
		;;
		*)
			message FAIL dev002 "" "$device has world permissions"
		;;
		esac
		fi
	done

}

echo
echo "# Checking device permissions..."

dirs="/dev"
# For Solaris but maintain compatibility with others
# (in Solaris /dev/ are symlinks to devices in /devices/pseudo)
[ -d /devices ] && dirs="$dirs /device"
[ -d /devices/pseudo ] && dirs="$dirs /devices/pseudo"
for dir in dirs
do
for file in $dirs/[a-z0-9]*
do
    	case $file in
	/dev/pty*|/dev/tty*|/devices/pseudo/pts*)
	# Do not check for virtual terminals
	;;
	/dev/urandom|/dev/random|/dev/zero|/dev/full)
	# Same for some special devices
	;;
	*)
	# Do not check directories or symbolic links
		if [ ! -d "$file"  -a  ! -h "$file" ] 
		then
		   check_dev_file $file
		fi
	;;
	esac
done
done

exit 0
