#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#     Copyright (C) 2002-2013 Javier Fernandez-Sanguino
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_issue - jfs - 11/10/2001
#
# Checks the /etc/issue and /etc/issue.net file to determine if they
# contain the appropriate content (this is defined in the ISSUEFILE and
# ISSUENETFILE)
#
# check_issue - 05/27/2002 - jfs
#        Changed TigerInstallDir to .
#
# check_issue - 08/09/2002 - jfs
#        Fixed some ! problems in Solaris by changing the ! DIFF to a
#        check of the exit status
#
# check_issue - 05/01/2003 - jfs - Fixed dependancies
#
# check_issue - 09/05/2013 - jfs - Change the requirement to have the ISSUEFILE
# and ISSUENETFILE. Instead, provide a different warning message if we do not 
# have any files to compare with.
#
#-----------------------------------------------------------------------------
# TODO:
# Make haveallfiles behave when /etc/issue is an empty file?:
# __fSize=( $(stat -t /etc/issue) )
# case "${__fSize[1]}" in 0) message WARN issue001w "" \
#"/etc/issue does not contain the designated content.";; esac
# 
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds DIFF || exit 1
  haveallfiles ISSUEFILE ISSUENETFILE BASEDIR WORKDIR || exit 1
  haveallvars TESTLINK HOSTNAME || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------

echo
echo "# Performing check of /etc/issue(s) login message..."

haveallcmds DIFF || exit 1
haveallfiles BASEDIR WORKDIR || exit 1

# for the local logins
if [ -e "$ISSUEFILE" ] ; then
	$DIFF -q /etc/issue $ISSUEFILE >/dev/null 2>&1
	if [ $? -ne 0 ] ; then
	   message WARN issue001w "" "/etc/issue does not contain the designated content."
	fi
else
	message WARN issue003w "" "No administrator-provided $ISSUEFILE found to compare /etc/issue with"
fi

# for the networked logins
if [ -e "$ISSUENETFILE" ] ; then
	$DIFF -q /etc/issue.net $ISSUENETFILE >/dev/null 2>&1
	if [ $? -ne 0 ] ; then
		message WARN issue002w "" "/etc/issue.net does not contain the designated content."
	fi
else
	message WARN issue003w "" "No administrator-provided $ISSUENETFILE found to compare /etc/issue.net with"
fi
