#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_issue - 11/10/2001
#
# check_issue - 05/27/2002 - jfs
#        Changed TigerInstallDir to .
#
# check_issue - 08/09/2002 - jfs
#        Fixed some ! problems in Solaris by changing the ! DIFF to a
#        check of the exit status
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds DIFF || exit 1
  haveallfiles ISSUEFILE ISSUENETFILE BASEDIR WORKDIR || exit 1
  haveallvars TESTLINK HOSTNAME
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------

echo
echo "# Performing check of /etc/issue(s) login message..."

haveallcmds DIFF || exit 1
haveallfiles ISSUEFILE ISSUENETFILE BASEDIR WORKDIR || exit 1

# for the local logins
$DIFF -q /etc/issue $ISSUEFILE >/dev/null 2>&1` ]
if [ $? -ne 0 ] 
  then
   message WARN issue001w "" "/etc/issue does not contain the designated content."
fi

# for the networked logins
$DIFF -q /etc/issue.net $ISSUENETFILE >/dev/null 2>&1
if [ $? -ne 0 ] 
  then
   message WARN issue002w "" "/etc/issue.net does not contain the designated content."
fi
