#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 2003 Javier Fernandez-Sanguino
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# integrit_run - 08/09/2003
# 
# Runs the integrit file checker and reports the results through the mesasging
# interface.
#
# 08/13/2003 - jfs - Respect the override (if done) from the site configuration
#                    file
# 
#-----------------------------------------------------------------------------
# TODO
# - Test further this script.
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds RM || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  haveallvars TESTLINK HOSTNAME Tiger_INTEGRIT_CFG
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------
echo
echo "# Running Integrit file checker..."

# Integrit binary location|override + default check
# Which, find, user-supplied var or tigexp's findcmd?:
if [ -z "$INTEGRIT" ] 
then
if [ -z "${Tiger_INTEGRIT_LOC_OVERRIDE}" ]
then
   INTEGRIT=`which integrit`
else
   INTEGRIT=${Tiger_INTEGRIT_LOC_OVERRIDE}
fi
fi

haveallcmds RM INTEGRIT || exit 1
haveallfiles BASEDIR WORKDIR || exit 1
haveallvars TESTLINK HOSTNAME Tiger_INTEGRIT_CFG || exit 1

# TODO: 
# - The location of integrit should be tested and not be
#   hardcoded in the script.

INTEGRIT_RPT="$WORKDIR/integrit.out.tmp.$$"
safe_temp $INTEGRIT_RPT
trap 'delete $INTEGRIT_RPT; exit 1' 1 2 3 15

$INTEGRIT -c -C $Tiger_INTEGRIT_CFG 2> /dev/null > $INTEGRIT_RPT

# TODO: calling INTEGRIT should check the errors (if any)
# i.e. check $? and determine what happened

# Differentiate between added, changed and removed files
for status in changed removed detected; do
	$GREP ${INTEGRIT_RPT} -e "^${status}:" | 
	$AWK '{ print $2; }' |
	while read result
	do
	case "${status}" in
		changed) exp="integ003w";;
		removed) exp="integ004w";;
		added)   exp="integ005w";;
	esac
	message WARN ${exp} "" "Detected ${status} for file ${result}"
	done
done

delete $INTEGRIT_RPT

exit 0
