#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# tripwire_run - 11/07/2001
# Paul Telford <paul_telford@hp.com>
#
# Runs tripwire (either a predefined location based on tigerrc) or 
# the version found in path to test filesystem integrity.
#
# tripwire_run - 08/13/2003 - jfs - Tripwire location is no longer hardcoded
# tripwire_run - 08/08/2003 - jfs - Temporary file creation.
# tripwire_run - 05/01/2003 - jfs - Fixed dependancies, awk -> $AWK
# tripwire_run - 07/25/2002 - jfs
#       Changed TigerInstallDir to .
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds AWK GREP || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  haveallvars TESTLINK HOSTNAME
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------
haveallcmds AWK GREP || exit 1
haveallfiles BASEDIR WORKDIR || exit 1
echo
echo "# Running Tripwire..."


tmplog="$WORKDIR/trip.out.tmp.$$"
safe_temp $tmplog
trap 'delete $tmplog; exit 1' 1 2 3 15

# Tripwire binary location|override + default check
# Which, find, user-supplied var or tigexp's findcmd?:
if [ -z "$TRIPWIRE" ]
then
if [ -z "${Tiger_TRIPW_LOC_OVERRIDE}" ]
then
        TRIPWIRE=`which tripwire`
else
        TRIPWIRE=${Tiger_TRIPW_LOC_OVERRIDE}
fi
fi

haveallcmds TRIPWIRE || exit 1

$TRIPWIRE --check 2> /dev/null | $GREP "Rule Name:" | $AWK '{print $NF}' > $tmplog

while read filename
do
	message FAIL trip01f "" "Detected modified file $filename"
done < $tmplog
	
delete $tmplog
exit 0
